---
- name: Ejecuta Jenkins OpenShift CICD
  hosts: localhost

  tasks:
    - name: echo ejecución API
      debug: msg="Iniciando ejecución API-Jenkins-OpenShift-CI\CD"
    - name: Llamada a API
      uri:
        url: "https://jenkins-cicdpoc.apps.cloud.igalvan.com/job/cicdpoc/job/cicdpoc-tasks-pipeline/build?token=97531"
        method: POST
        user: "dv-admin"
        password: "a86945fa128da756b6094e4e3427bcb8"
        force_basic_auth: yes
        status_code: 201
        validate_certs: no
        body_format: json
